# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xuanming/Desktop/Laplace-equation-with-Trilinos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xuanming/Desktop/Laplace-equation-with-Trilinos/build-nvcc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuanming/Desktop/Laplace-equation-with-Trilinos/build-nvcc/CMakeFiles /home/xuanming/Desktop/Laplace-equation-with-Trilinos/build-nvcc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuanming/Desktop/Laplace-equation-with-Trilinos/build-nvcc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named laplace_fem_core

# Build rule for target.
laplace_fem_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laplace_fem_core
.PHONY : laplace_fem_core

# fast build rule for target.
laplace_fem_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/build
.PHONY : laplace_fem_core/fast

#=============================================================================
# Target rules for targets named laplace_fem_2d

# Build rule for target.
laplace_fem_2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laplace_fem_2d
.PHONY : laplace_fem_2d

# fast build rule for target.
laplace_fem_2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_2d.dir/build.make CMakeFiles/laplace_fem_2d.dir/build
.PHONY : laplace_fem_2d/fast

src/Assembler.o: src/Assembler.cpp.o
.PHONY : src/Assembler.o

# target to build an object file
src/Assembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/Assembler.cpp.o
.PHONY : src/Assembler.cpp.o

src/Assembler.i: src/Assembler.cpp.i
.PHONY : src/Assembler.i

# target to preprocess a source file
src/Assembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/Assembler.cpp.i
.PHONY : src/Assembler.cpp.i

src/Assembler.s: src/Assembler.cpp.s
.PHONY : src/Assembler.s

# target to generate assembly for a file
src/Assembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/Assembler.cpp.s
.PHONY : src/Assembler.cpp.s

src/LinearSolver.o: src/LinearSolver.cpp.o
.PHONY : src/LinearSolver.o

# target to build an object file
src/LinearSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/LinearSolver.cpp.o
.PHONY : src/LinearSolver.cpp.o

src/LinearSolver.i: src/LinearSolver.cpp.i
.PHONY : src/LinearSolver.i

# target to preprocess a source file
src/LinearSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/LinearSolver.cpp.i
.PHONY : src/LinearSolver.cpp.i

src/LinearSolver.s: src/LinearSolver.cpp.s
.PHONY : src/LinearSolver.s

# target to generate assembly for a file
src/LinearSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/LinearSolver.cpp.s
.PHONY : src/LinearSolver.cpp.s

src/MeshGenerator.o: src/MeshGenerator.cpp.o
.PHONY : src/MeshGenerator.o

# target to build an object file
src/MeshGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/MeshGenerator.cpp.o
.PHONY : src/MeshGenerator.cpp.o

src/MeshGenerator.i: src/MeshGenerator.cpp.i
.PHONY : src/MeshGenerator.i

# target to preprocess a source file
src/MeshGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/MeshGenerator.cpp.i
.PHONY : src/MeshGenerator.cpp.i

src/MeshGenerator.s: src/MeshGenerator.cpp.s
.PHONY : src/MeshGenerator.s

# target to generate assembly for a file
src/MeshGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/MeshGenerator.cpp.s
.PHONY : src/MeshGenerator.cpp.s

src/PostProcessor.o: src/PostProcessor.cpp.o
.PHONY : src/PostProcessor.o

# target to build an object file
src/PostProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/PostProcessor.cpp.o
.PHONY : src/PostProcessor.cpp.o

src/PostProcessor.i: src/PostProcessor.cpp.i
.PHONY : src/PostProcessor.i

# target to preprocess a source file
src/PostProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/PostProcessor.cpp.i
.PHONY : src/PostProcessor.cpp.i

src/PostProcessor.s: src/PostProcessor.cpp.s
.PHONY : src/PostProcessor.s

# target to generate assembly for a file
src/PostProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/PostProcessor.cpp.s
.PHONY : src/PostProcessor.cpp.s

src/ProblemData.o: src/ProblemData.cpp.o
.PHONY : src/ProblemData.o

# target to build an object file
src/ProblemData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/ProblemData.cpp.o
.PHONY : src/ProblemData.cpp.o

src/ProblemData.i: src/ProblemData.cpp.i
.PHONY : src/ProblemData.i

# target to preprocess a source file
src/ProblemData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/ProblemData.cpp.i
.PHONY : src/ProblemData.cpp.i

src/ProblemData.s: src/ProblemData.cpp.s
.PHONY : src/ProblemData.s

# target to generate assembly for a file
src/ProblemData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/ProblemData.cpp.s
.PHONY : src/ProblemData.cpp.s

src/TriangleElement.o: src/TriangleElement.cpp.o
.PHONY : src/TriangleElement.o

# target to build an object file
src/TriangleElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/TriangleElement.cpp.o
.PHONY : src/TriangleElement.cpp.o

src/TriangleElement.i: src/TriangleElement.cpp.i
.PHONY : src/TriangleElement.i

# target to preprocess a source file
src/TriangleElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/TriangleElement.cpp.i
.PHONY : src/TriangleElement.cpp.i

src/TriangleElement.s: src/TriangleElement.cpp.s
.PHONY : src/TriangleElement.s

# target to generate assembly for a file
src/TriangleElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/TriangleElement.cpp.s
.PHONY : src/TriangleElement.cpp.s

src/TriangleQuadrature.o: src/TriangleQuadrature.cpp.o
.PHONY : src/TriangleQuadrature.o

# target to build an object file
src/TriangleQuadrature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/TriangleQuadrature.cpp.o
.PHONY : src/TriangleQuadrature.cpp.o

src/TriangleQuadrature.i: src/TriangleQuadrature.cpp.i
.PHONY : src/TriangleQuadrature.i

# target to preprocess a source file
src/TriangleQuadrature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/TriangleQuadrature.cpp.i
.PHONY : src/TriangleQuadrature.cpp.i

src/TriangleQuadrature.s: src/TriangleQuadrature.cpp.s
.PHONY : src/TriangleQuadrature.s

# target to generate assembly for a file
src/TriangleQuadrature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_core.dir/build.make CMakeFiles/laplace_fem_core.dir/src/TriangleQuadrature.cpp.s
.PHONY : src/TriangleQuadrature.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_2d.dir/build.make CMakeFiles/laplace_fem_2d.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_2d.dir/build.make CMakeFiles/laplace_fem_2d.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplace_fem_2d.dir/build.make CMakeFiles/laplace_fem_2d.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... laplace_fem_2d"
	@echo "... laplace_fem_core"
	@echo "... src/Assembler.o"
	@echo "... src/Assembler.i"
	@echo "... src/Assembler.s"
	@echo "... src/LinearSolver.o"
	@echo "... src/LinearSolver.i"
	@echo "... src/LinearSolver.s"
	@echo "... src/MeshGenerator.o"
	@echo "... src/MeshGenerator.i"
	@echo "... src/MeshGenerator.s"
	@echo "... src/PostProcessor.o"
	@echo "... src/PostProcessor.i"
	@echo "... src/PostProcessor.s"
	@echo "... src/ProblemData.o"
	@echo "... src/ProblemData.i"
	@echo "... src/ProblemData.s"
	@echo "... src/TriangleElement.o"
	@echo "... src/TriangleElement.i"
	@echo "... src/TriangleElement.s"
	@echo "... src/TriangleQuadrature.o"
	@echo "... src/TriangleQuadrature.i"
	@echo "... src/TriangleQuadrature.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

